[package]
name = "iotsecretary"
version = "0.1.0"
authors = ["Bradley Nelson <bradleynelson102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
